#!/bin/bash
cp ../../cat/cat_source/build/libcat.so dependencies/cat/
cp -r ../../cat/cat_source/include dependencies/cat/
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build
cp build/compile_commands.json ../

cd build
echo making
cmake ..
echo building
cmake --build . --target clean

